version: '3.8'



services:
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATABASE="Amazon"
    ports:
      - 27017:27017
  # mongo-express:
  #   container_name: mongo-express
  #   image: mongo-express
  #   ports:
  #     - 8081:8081
  #   depends_on:
  #     - mongo
  #   environment:
  #     - ME_CONFIG_MONGODB_PORT=27017
  #     - ME_CONFIG_MONGODB_SERVER=mongo
